### ISSUE TITLE
Invites: Show rejected invites to reconsider?

### ISSUE THREAD

**Issue by Raeki** [tomo-tabi/front-end-tomo-tabi#70]

**Comment by YJK-7** [comment]
Question: should we forever show a rejected invite? I think it will be a little weird to just see that the whole time so maybe  users have an option to delete rejected invites? (like ok I checked it make it go way?)

**Comment by Raeki** [comment]
I think deleting them is good. Would help clear "unneeded" data from the backend database. 

This would also allow for the resending of accidentally rejected invites.

**Comment by YJK-7** [comment]
- #112
